### ISSUE TITLE
やること

### ISSUE THREAD

**Issue by shxun6934** [sg1021/dogTest#3]

**Comment by sg1021** [comment]
ラズパイの中にある、pythonスクリプトの整理（おすわり）

**Comment by sg1021** [comment]
Arduinoによる「おすわり」動作プログラム試作を作製

**Comment by sg1021** [comment]
Arduinoによる「おすわり」動作プログラム試作が完成したので、gitに上げる

**Comment by sg1021** [comment]
pythonで1つのモータを動かすプログラムを作製して、gitに上げる
